# ===============================
# = SERVER
# ===============================
server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api}

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    sk.janobono.example: ${LOG_LEVEL:debug}

# ===============================
# = SPRING DOC
# ===============================
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
